name: nikata
description: A Geofence-triggered notification app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  async: ^2.11.0
  permission_handler: ^10.2.0
  url_launcher: ^6.2.0
  flutter_map_location_marker: ^8.0.5
  geolocator: ^11.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  flutter_svg: ^0.22.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
